#!/usr/bin/env node
/**
 * update-index.js
 *
 * Scans all chapter content files (content/chapter-NN.md) for Key Terms
 * tables and regenerates docs/index.md — a comprehensive alphabetical index
 * of every defined term with its chapter reference.
 *
 * Key Terms are expected in the standard chapter format:
 *
 *   ## Key Terms
 *   | Term | Brief Definition |
 *   |------|-----------------|
 *   | **Term Name** | Definition text |
 *
 * Usage:  node scripts/update-index.js
 */

'use strict';

const fs   = require('fs');
const path = require('path');

// ── Paths ──────────────────────────────────────────────────────────────────
const ROOT         = path.resolve(__dirname, '..');
const CONTENT_DIR  = path.join(ROOT, 'content');
const INDEX_FILE   = path.join(ROOT, 'docs', 'foundations-of-nursing', 'index.md');

// ── Parse a single chapter file ───────────────────────────────────────────
// Returns an array of { term, definition } objects extracted from the
// Key Terms table in the chapter, along with the chapter number and title.
function parseChapter(filePath) {
  const text  = fs.readFileSync(filePath, 'utf8');
  const lines = text.split('\n');

  // Extract chapter number and title from the first H1 heading
  let chapterNum   = null;
  let chapterTitle = '';
  const h1Match = text.match(/^#\s+Chapter\s+(\d+)\s*[:\u2014\-]\s*(.+)$/m);
  if (h1Match) {
    chapterNum   = parseInt(h1Match[1], 10);
    chapterTitle = h1Match[2].trim();
  } else {
    // Fall back to deriving chapter number from the filename (chapter-NN.md)
    const fnMatch = path.basename(filePath).match(/chapter-(\d+)\.md$/i);
    if (fnMatch) {
      chapterNum   = parseInt(fnMatch[1], 10);
      chapterTitle = `Chapter ${chapterNum}`;
    }
  }

  if (chapterNum === null) return null;

  // Locate the Key Terms section and extract table rows
  const terms = [];
  let inKeyTerms  = false;
  let inTable     = false;

  for (const line of lines) {
    const trimmed = line.trim();

    // Detect the start of the Key Terms section
    if (/^##\s+Key Terms/i.test(trimmed)) {
      inKeyTerms = true;
      inTable    = false;
      continue;
    }

    // Stop collecting when we reach the next ## section
    if (inKeyTerms && /^##\s+/.test(trimmed) && !/^##\s+Key Terms/i.test(trimmed)) {
      break;
    }

    if (!inKeyTerms) continue;

    // Detect table rows (lines that start and end with |)
    if (trimmed.startsWith('|')) {
      // Skip header/separator rows — rows whose first cell has no bold text
      // and rows composed entirely of dashes and pipes
      if (/^\|[-\s|]+\|$/.test(trimmed)) continue;  // separator row

      const cells = trimmed
        .split('|')
        .map(c => c.trim())
        .filter(c => c.length > 0);

      if (cells.length < 2) continue;

      const rawTerm = cells[0];
      const rawDef  = cells[1];

      // Extract the term name from **Term Name** bold Markdown
      const termMatch = rawTerm.match(/\*\*(.+?)\*\*/);
      if (!termMatch) continue;   // skip header row or non-bold cells

      const term       = termMatch[1].trim();
      const definition = rawDef.replace(/\*\*/g, '').trim();

      if (term && definition) {
        terms.push({ term, definition });
        inTable = true;
      }
    } else if (inTable && trimmed === '') {
      // Blank line after the table — Key Terms section is done
      break;
    }
  }

  return { chapterNum, chapterTitle, terms };
}

// ── Collect entries from all chapter files ────────────────────────────────
function collectEntries() {
  if (!fs.existsSync(CONTENT_DIR)) {
    console.warn(`update-index: content directory not found (${CONTENT_DIR}), no terms to index.`);
    return [];
  }

  const files = fs.readdirSync(CONTENT_DIR)
    .filter(f => /^chapter-\d+\.md$/i.test(f))
    .sort();

  const entries = [];   // { term, definition, chapterNum, chapterTitle }

  for (const file of files) {
    const result = parseChapter(path.join(CONTENT_DIR, file));
    if (!result) continue;
    const { chapterNum, chapterTitle, terms } = result;
    for (const { term, definition } of terms) {
      entries.push({ term, definition, chapterNum, chapterTitle });
    }
  }

  return entries;
}

// ── Build the index Markdown ───────────────────────────────────────────────
function buildIndex(entries) {
  // Sort alphabetically, case-insensitive
  entries.sort((a, b) => a.term.toLowerCase().localeCompare(b.term.toLowerCase()));

  const now = new Date().toISOString().slice(0, 10);

  const lines = [
    '# Foundations of Nursing — Index',
    '',
    `*Comprehensive alphabetical index of key terms defined across all chapters.*  `,
    `*Last updated: ${now}*`,
    '',
    '> **Note:** This file is automatically regenerated by `scripts/update-index.js`',
    '> whenever a commit is made. Do not edit it by hand.',
    '',
    '---',
    '',
  ];

  if (entries.length === 0) {
    lines.push('*No key terms found in content files. Index will be populated as chapters are drafted.*');
    lines.push('');
    return lines.join('\n');
  }

  // Group entries by first letter
  let currentLetter = '';
  for (const entry of entries) {
    const firstChar = entry.term[0].toUpperCase();
    const letter    = /[A-Z]/.test(firstChar) ? firstChar : '#';

    if (letter !== currentLetter) {
      currentLetter = letter;
      lines.push(`## ${letter}`);
      lines.push('');
      lines.push('| Term | Definition | Chapter |');
      lines.push('|------|------------|---------|');
    }

    const chapterRef = entry.chapterTitle
      ? `Ch. ${entry.chapterNum} — ${entry.chapterTitle}`
      : `Ch. ${entry.chapterNum}`;

    // Escape backslashes first, then pipe characters, for safe Markdown table cells
    const safeTerm = entry.term.replace(/\\/g, '\\\\').replace(/\|/g, '\\|');
    const safeDef  = entry.definition.replace(/\\/g, '\\\\').replace(/\|/g, '\\|');
    const safeRef  = chapterRef.replace(/\\/g, '\\\\').replace(/\|/g, '\\|');

    lines.push(`| **${safeTerm}** | ${safeDef} | ${safeRef} |`);
  }

  const uniqueChapters = new Set(entries.map(e => e.chapterNum)).size;

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`*${entries.length} term${entries.length !== 1 ? 's' : ''} indexed across ${
    uniqueChapters
  } chapter${uniqueChapters !== 1 ? 's' : ''}.*`);
  lines.push('');

  return lines.join('\n');
}

// ── Main ───────────────────────────────────────────────────────────────────
function main() {
  console.log('update-index: scanning content files…');
  const entries = collectEntries();
  console.log(`update-index: found ${entries.length} key term(s) across ${
    new Set(entries.map(e => e.chapterNum)).size
  } chapter file(s).`);

  const markdown = buildIndex(entries);
  fs.writeFileSync(INDEX_FILE, markdown, 'utf8');
  console.log(`update-index: wrote ${INDEX_FILE}`);
}

main();
